// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jFQLfk1m41Amgf3T1fkM0l5zJQJzNHU',
    appId: '1:976280048076:web:8c9f66821b493eb9190d69',
    messagingSenderId: '976280048076',
    projectId: 'bookapp-prod',
    authDomain: 'bookapp-prod.firebaseapp.com',
    storageBucket: 'bookapp-prod.appspot.com',
    measurementId: 'G-E468D61SJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGq6-RXLYefEwnPEeBvz3GvuQTpsnVKAs',
    appId: '1:976280048076:android:1db0bffd5c6ac0d4190d69',
    messagingSenderId: '976280048076',
    projectId: 'bookapp-prod',
    storageBucket: 'bookapp-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3k4JURBYh2OXSPh1oCWE-vpdi9JB21C8',
    appId: '1:976280048076:ios:2c65df684821b3fc190d69',
    messagingSenderId: '976280048076',
    projectId: 'bookapp-prod',
    storageBucket: 'bookapp-prod.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3k4JURBYh2OXSPh1oCWE-vpdi9JB21C8',
    appId: '1:976280048076:ios:7ad8f494dc159dd2190d69',
    messagingSenderId: '976280048076',
    projectId: 'bookapp-prod',
    storageBucket: 'bookapp-prod.appspot.com',
    iosBundleId: 'com.example.book.RunnerTests',
  );
}
